### ISSUE TITLE
"Stat" <- ?

### ISSUE THREAD

**Issue by xrtw** [Burn-One-Studios/B1-skillz#4]
what stands "Stat" for in Config.Skills ?

**Comment by Kingsage311** [comment]
That's the native GTAO skill hash so, for instance, you notice that there's no logic in the script to make the skills do something when you increase the level but all the stats already have functionality built in due to the hash so if you level up you're strength then you will do more unarmed damage or if you level up your shooting you will have less recoil etc etc, if you wish to make a custom skill that can be an empty string or whatever you want to put in the string but then you will have to write your own functionality for it.

**Comment by Kingsage311** [comment]
If you have any more questions im more than happy to answer them here but the preferred method unless it's a bug, error, or just not working is to ask in the discord link: https://discord.gg/d7CxSVgxaX I will be closing this issue for now but your still more than welcome to comment on it.

**Comment by xrtw** [comment]
> That's the native GTAO skill hash so, for instance, you notice that there's no logic in the script to make the skills do something when you increase the level but all the stats already have functionality built in due to the hash so if you level up you're strength then you will do more unarmed damage or if you level up your shooting you will have less recoil etc etc, if you wish to make a custom skill that can be an empty string or whatever you want to put in the string but then you will have to write your own functionality for it.

sorry..... i meant "icon"
fas fa-walking <- this for example. because it also saves in mysql but is not shown in skill menu
